ssbc/patchwork-ui

src/apis/phoenix-feed.js, src/gui/com/adverts.js, src/gui/com/message-summary.js, src/gui/com/message-thread.js, src/gui/com/message.js, src/gui/pages/adverts.js, src/mans/phoenix-feed.js
=> simplified message types

package.json, src/lib/markdown.js, src/lib/util.js
I have taken the liberty to start refactoring out parts.
I think this will make the code easier to navigate & understand & contribute to.
The date formatter was a low hanging fruit, i think there are other parts we could pull out too.
=> refactor out generalized parts

src/gui/pages/address-book.js, src/gui/pages/profile.js
your trust and flag edges now show in address book (half of #251)
book is now ordered to show followed/trusted at top and flagged at bottom
=> address book tweaks

package.json, src/gui/com/message-summary.js, src/gui/com/post-form.js, src/gui/index.js, src/lib/markdown.js
this is a couple of bugfixes and improvements to @-mentions. most notable, during compose you no longer see the id get inserted into your textbox -- you'll see `@bob` like you typed
=> @-mention improvements

src/app.js, src/pages/adverts.js, src/pages/feed.js, src/pages/inbox.js, src/pages/posts.js
=> added Get Latests btn to posts page (close #265)

package.json, src/com/message-summary.js, src/pages/posts.js
=> non-posts with replies now render in the posts page (close #264)

package.json, src/app.js, src/com/addresses.js, src/com/index.js, src/com/message-summary.js, src/com/message.js, src/pages/profile.js
closes https://github.com/ssbc/phoenix/issues/270]
=> better name-confidence indicators

src/com/post-form.js, src/lib/markdown.js
=> visual indication of bad @-mentions

less/com/message-summary.less, less/home.less, src/com/index.js, src/pages/help.js, src/pages/profile.js
=> profile pages now show follow, trust, and flag relations

blobs.js, index.js
add a `/ext/<hash>` route to the server to serve blobs
=> blob hosting

blobs.js, index.js, less/com/ext.less, package.json, src/com/advert-form.js, src/com/adverts.js, src/com/message.js, src/com/post-form.js, src/pages/adverts.js, src/pages/compose.js, src/pages/ext.js
=> add more file viewing tools

package.json, src/app.js, src/com/index.js
with this PR, the user's own posts no longer show in the inbox, and replies/mentions to the user now show in the document title as a pending message
=> new content notification improvements

less/com/ext.less, less/com/message-summary.less, less/com/message-thread.less, less/com/message.less, less/variables.less
=> style tweaks

src/app.js, src/com/addresses.js, src/com/peers.js, src/lib/ssb-manifest.js
waiting on https://github.com/ssbc/scuttlebot/pull/99
=> add manual sync and "last connect" status info to peers in the address book

less/com/ext.less, less/com/message-summary.less, less/com/message.less, less/com/post-form.less, src/app.js, src/com/addresses.js, src/com/message-summary.js, src/com/message-thread.js, src/com/message.js, src/lib/util.js, src/pages/message.js
refer to the commit messages to see the changes
=> a bundle of ux updates

package.json
=> use browserify in --debug mode

src/com/index.js, src/pages/inbox.js, src/pages/posts.js
=> switch from "load more" to pagination

src/com/message-summary.js
=> mentions and author are now links to prof pages in messages summaries

less/com/message-feed.less, less/com/message-summary.less, less/com/message-thread.less, less/home.less, less/variables.less, package.json, src/app.js, src/com/message-feed.js, src/com/message-summary.js, src/com/message-thread.js, src/com/message-visuals.js, src/com/post-form.js, src/com/pretty-raw.js, src/pages/inbox.js, src/pages/message.js, src/pages/posts.js, src/pages/profile.js
=> Update the inbox

package.json, src/com/message-summary.js, src/com/notifications.js, src/pages/address-book.js, src/pages/profile.js
per https://github.com/ssbc/phoenix/issues/340#issuecomment-80677791
=> update feed-aliasing to the 'alias' attr scheme

less/com/addresses.less, less/com/header-controls.less, less/com/hexagon.less, less/com/message-feed.less, less/com/message-summary.less, less/com/message-thread.less, less/com/message.less, less/com/post-form.less, less/home.less, src/com/address.js, src/com/index.js, src/com/message-summary.js, src/com/message-thread.js, src/com/pretty-raw.js, src/pages/address-book.js, src/pages/adverts.js, src/pages/compose.js, src/pages/inbox.js, src/pages/message.js, src/pages/posts.js
continuing the design tweaking
=> more design work

less/com/addresses.less, less/com/hexagon.less, less/com/image-uploader.less, less/com/message-summary.less, less/com/message-thread.less, less/com/message.less, less/com/profile.less, src/com/address.js, src/com/image-uploader.js, src/com/index.js, src/com/message-summary.js, src/pages/address-book.js, src/pages/profile.js
Another day, another big UI PR
=> Today's UI updates

index.js
fixes https://github.com/ssbc/phoenix/issues/356
=> allow gui requests by ::1 (ipv6 loopback)

src/home.js
fixes https://github.com/ssbc/phoenix/issues/372
=> use window.location.host to get local sbot addr

html/home.html, src/com/index.js, src/com/message-feed.js, src/home.js, src/pages/feed.js, src/pages/home.js, src/pages/inbox.js, src/pages/profile.js
=> May 2 tweaks

lib/com/message.js
=> fix: thread is not defined

less/com/message.less
a best guess at solving this problem :
=> add max-width to mardown included images

less/com/post-form.less
I'm not sure the best way to test this. I'm perhaps 70% confident I've hit the right style :P
=> make a the comment preview style different enough that it doesn't look editable

lib/markdown.js
check out `%HDEEFOT1InerZyjsbgHtBxOiTHpXVO7xUcTQLN+PWDg=.sha256`
and inspect the code to confirm the pattern looks right
=> auto-include links to blobs for markdown images
